### ISSUE TITLE
post 之后遇到的问题

### ISSUE THREAD

**Issue by qiuxiaojian** [Zzzia/qiniuToken#1]
按照描述请求后出现了，报错信息
![image](https://user-images.githubusercontent.com/34261007/53473047-5bc20400-3aa4-11e9-955c-29aa0489ca48.png)

**Comment by Zzzia** [comment]
嗯，不好意思，以前不知道怎么写javaweb，请求方式有点不太一样
可以换成这样试试
http://zzzia.net:8080/qiniu/?accessKey=1&secretKey=2&bucket=3
直接把参数写在url里，请求方式设置为post

**Comment by turboleee** [comment]
你好我将参数写在url之后出现问题说服务器返回数据格式错误
{"msg":"服务器返回数据格式错误","body":"{\n \"status\": 200,\n \"info\": \"success\",\n \"token\": \"\"C399vy_daXRD_BppaEGKMT81mGA5KkqDqvLHUjCx\":codSJhGBuA391cfqJ6YbUVN-Vhw=:eyJzY29wZSI6IiJ0ZXN0IiIsImRlYWRsaW5lIjoxNTU4MTY1ODYxfQ==\"\n}","statusCode":200,"code":3} at tea_post_frm.html : 217

**Comment by Zzzia** [comment]
6.17
已更新请求方式，添加了GET方法，若POST有问题直接使用GET即可
